import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import type { Metadata } from 'next'
import './globals.css'
import type { PropsWithChildren } from 'react'
import { Orbitron, Exo_2 } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const orbitron = Orbitron({ subsets: ['latin'], variable: '--font-orbitron' })
const exo2 = Exo_2({ subsets: ['latin'], variable: '--font-exo2' })

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
       className={`${orbitron.variable} ${exo2.variable}`}
       style={{
        backgroundImage: `url('/bg2.png')`,
        backgroundSize: "cover",
        backgroundRepeat: "no-repeat",
        backgroundPosition: "center",
        height: "100vh",
      }}>
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </body>
    </html>
  )
}
